apiVersion : apps/v1
kind: Deployment
metadata:
  name: "devopskubernetescluster-726c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "devopskubernetescluster-726c"
  template:
    metadata:
      labels:
        app: "devopskubernetescluster-726c"
    spec:
      containers:
        - name: "devopskubernetescluster-726c"
          image: "devopsbootcamptest.azurecr.io/devopskubernetescluster"
          ports:
          - containerPort: 8080